### PR TITLE
I2s Task with ringbuffer (as per Espessif)

### PR DESCRIPTION
**Pull request by mitchjs**
Code still needs cleanup and commenting
and put the Internal DAC option in the new task

### CODE REVIEW

**Comment by pschatzmann** [comment]
Cool, the changes are visible now! 
Can you confirm that you also tested with the I2S buffer set to the same size before you implemented the ringbuffer. 
I still have the feeling that you just added an additional buffer instead of increasing the current  buffering concept.

**Comment by mitchjs** [comment]
i2s buffer? you mean the DMA Buffers?
.dma_buf_count = 8,
.dma_buf_len = 64,
if so, yours is ALREADY larger than the Espressif Example, and yes i messed with them
the key difference is thier A2DP example, uses the ringbuffer and processes the audio data on its own small task
so really its them implementing the ring buffer, i just copied it in :)

for sure this should be tested by a few people... and some code cleanup/comments need to be done

**Comment by pschatzmann** [comment]
Yes,If you use 
.dma_buf_count = 4,
.dma_buf_len = 1024,
I would have expected that this might have had the same effect like your additional ring buffer.

**Comment by mitchjs** [comment]
reading up on those two settings:

int dma_buf_count
The total number of DMA buffers to receive/transmit data. A descriptor includes some information such as buffer address, the address of the next descriptor, and the buffer length. Since one descriptor points to one buffer, therefore, ‘dma_desc_num’ can be interpreted as the total number of DMA buffers used to store data from DMA interrupt. Notice that these buffers are internal to’i2s_read’ and descriptors are created automatically inside of the I2S driver. Users only need to set the buffer number while the length is derived from the parameter described below.

int dma_buf_len
Number of frames in a DMA buffer. A frame means the data of all channels in a WS cycle. The real_dma_buf_size = dma_buf_len * chan_num * bits_per_chan / 8. For example, if two channels in stereo mode (i.e., ‘channel_format’ is set to ‘I2S_CHANNEL_FMT_RIGHT_LEFT’) are active, and each channel transfers 32 bits (i.e., ‘bits_per_sample’ is set to ‘I2S_BITS_PER_CHAN_32BIT’), then the total number of bytes of a frame is ‘channel_format’ * ‘bits_per_sample’ = 2 * 32 / 8 = 8 bytes. We assume that the current ‘dma_buf_len’ is 100, then the real length of the DMA buffer is 8 * 100 = 800 bytes. Note that t**he length of an internal real DMA buffer shouldn’t be greater than 4092.**

so 4, 1024 prob not good idea :)

**Comment by pschatzmann** [comment]
Ok, so if I get it right it's more an issue with priorities than with the buffer size. In the end there must be a reason why the Espressif example has introduced the additional I2S task lately...

**Comment by pschatzmann** [comment]
Hmm - so, setting the log level to error would have have resolved the issue as well... ?

**Comment by mitchjs** [comment]
i dont know... thats why i asked that follow up question
im running at INFO, really its any logging i guess... in that task... causes the other task to starve for time

**Comment by mitchjs** [comment]
im cleaning up the code a bit, but no idea yet how to update github... hacking way through that
i did push, and it updated my master branch not the i2s task branch
ugh git so confusing

**Comment by mitchjs** [comment]
hey i got it... i made a change locally and pushed it... now needs merge

**Pull request merged**
