### PR TITLE
compatible device callback

### PR DESCRIPTION
**Pull request by degnarraer**
We talked about this many months ago, but I created a callback that a subclass of your class can register for a "New Device Found" callback It is called every time filter_inquiry_scan_result is called and a compatible device is found. I pass out the name of the device and the RSSI value. This allows the subclass to keep track of compatible devices and their RSSI so that eventually, it can select the one it wants to connect to.

In my case, my sub class, not shown in this code, maintains a vector of compatible devices and uses the millis() time the last time we heard from the device via this new call back.... and after 5 seconds, without a call, I purge them from my vector.

However, the issue I have right now is, HOW DO WE GET filter_inquiry_scan_result to be called without first "starting" the bluetooth source with some NAME that we do not yet know..... 

I can get this to work if I put in an empty string or something else as the device to connect to. It would be nice if you could provide a way for the Bluetooth source to start without a name... but using "" seems to work for now.

### CODE REVIEW

**Comment by pschatzmann** [comment]
If I understand you correctly you just need to get informed about the scan results.
I would actually prefer to have a simple callback method instead of all these new classes. That would fit much better with the current way of handling things.
From an user perspective something as follows:
```
bool isValid(const char* ssid, int rssi){
   // return true to connect
}
setSSIDCallback(isValid);
```
where setSSIDCallback is just defined as
```
void setSSIDCallback(bool(*const char*ssid, int rrsi)());
```
We can also add a start method w/o name which just calls start with an empty list.

**Comment by degnarraer** [comment]
I don't want to have to KNOW the SSID ahead of time. I want to be able to scan for all compatible devices so that I can populate a UI with the available devices. AKA, I want to scan for devices, then once I have a list of them, I want to be able to pick from that list.

**Comment by pschatzmann** [comment]
But this is exactly what I was proposing. You register the callback and this way you get notified about the available SSIDs.
You return true when the user has selected the corresponding entry from your list.

**Comment by degnarraer** [comment]
How do we start the process of "Scanning" for devices? Are you able to create a new function that starts scanning for devices without "Starting" the Source or do you want me to continue to use the empty string SSID?

**Comment by pschatzmann** [comment]
I will add 
```
    /// Starts w/o indicating the name. Connections will be managed via setSSIDCallback()
    virtual void start(music_data_channels_cb_t callback = NULL)) {
        std::vector<const char*> names; // empty vector
        start(names, callback);
    }
```

**Comment by pschatzmann** [comment]
I just committed my described changes. Please have a look at the [example](https://github.com/pschatzmann/ESP32-A2DP/blob/main/examples/bt_music_sender_ssid_callback/bt_music_sender_ssid_callback.ino)

**Comment by degnarraer** [comment]
Shoot. I implemented a change on my branch that resolves all of the issues you had and resolves my issue as well. Let me figure out how to make my push to this branch visible. I may need to submit a new Merge Request.

**Comment by degnarraer** [comment]
Looks like you can see the changes in the commits above.

**Comment by degnarraer** [comment]
Ahhh I see that I landed on the same solution that you implemented aside from naming. Nice job!

**Comment by pschatzmann** [comment]
So I can ignore this request. The only thing from your changes that I would like to keep is the renameing of the variable name from callback  to music_data_channels_cb

**Comment by degnarraer** [comment]
Excellent!

**Comment by degnarraer** [comment]
FYI, I very much appreciate this library!

**Review by degnarraer — COMMENTED** [review]
Look great

**Comment by degnarraer** [comment]
I found that you are missing the start_raw equivalent that doesn't require a name. Please add that as well.

**Comment by pschatzmann** [comment]
why would this be necessary?

**Pull request closed without merging**
