### PR TITLE
Update

### PR DESCRIPTION
**Pull request by tv4you2016**
V1.0.4

add callback bt_volumechange;
fix I2S_COMM_FORMAT_I2S_MSB attribute((deprecated)) = 0x01, /!< I2S format MSB, (I2S_COMM_FORMAT_I2S |I2S_COMM_FORMAT_I2S_MSB) correspond to I2S_COMM_FORMAT_STAND_I2S/
V1.0.3

fix volume control
V1.0.2

add volume control
add set volume control (setVolume(uint8_t volume);)
add get volume control (getVolume())
V1.0.1

Remove BluetoothA2DPSource

### CODE REVIEW

**Comment by pschatzmann** [comment]
add callback bt_volumechange;
fix I2S_COMM_FORMAT_I2S_MSB attribute((deprecated)) = 0x01, /!< I2S format MSB, (I2S_COMM_FORMAT_I2S |I2S_COMM_FORMAT_I2S_MSB) correspond to I2S_COMM_FORMAT_STAND_I2S/
add volume control
add set volume control (setVolume(uint8_t volume);)
add get volume control (getVolume())

**Comment by pschatzmann** [comment]
I just noticed that this is not working with Arduino. With which ESP IDF Release did you work ?
What range is expected for the volume ?
To support Arduino, I commited a couple of changes - can you help me to verify them ?

**Comment by tv4you2016** [comment]
@pschatzmann  
Hello arduino Ide works yes, I used IDE 1.8.15 with
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

range of volume is 0-100

**Comment by pschatzmann** [comment]
Strange: I have also upgraded to IDE 1.8.15. If I check in the Library Manager I am using the latest esp32 version 1.0.6

But I still get compile errors like

/Users/pschatzmann/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.h:56:36: error: 'esp_avrc_tg_cb_event_t' has not been declared
     static void app_rc_tg_callback(esp_avrc_tg_cb_event_t event, esp_avrc_tg_cb_param_t *param);
                                    ^

When I compile direcly in IDF it is working fine.  What version are you getting in the Library manager ?

**Comment by tv4you2016** [comment]
image


image

**Comment by pschatzmann** [comment]
I am speechless! 

I tried the very same thing on different machines and also with your project but I always end up with the same compile errors...

Can you go to the Tools -> Board -> Board Manager.
Search for ESP32 and tell me the version that you have installed.

At the moment I have no idea what could be different...

**Comment by tv4you2016** [comment]
image

**Comment by tv4you2016** [comment]
remember me, remove the arduino ide , then go to :
C:\Users\user\AppData\Local\

remove the Arduino15 folder, then install the arduino ide 1.8.15 add:

https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
 
Now you can install the latest 2.0.0-rc1 version from the boards manager


then try downloading the lib https://github.com/tv4you2016/ESP32-A2DP-1
add to arduino ide
and try to compile the example:

bt_music_receiver_simple.ino

**Comment by tv4you2016** [comment]
'esp_avrc_tg_cb_event_t' has not been declared 

INCLUDE Header File **esp_avrc_api.h**

**Comment by pschatzmann** [comment]
Ah, finally I understand: I must have overlooked that you did not use the official Platform URL for the ESP32 but the development one...

Thanks a lot for your help...

**Pull request merged**
