### PR TITLE
Added in Bluetooth Discovery Mode callback

### PR DESCRIPTION
**Pull request by degnarraer**
Added in a callback that is similar to the SSID_callback. The new callback allows you to be notified when the Discovery Mode changes.

### CODE REVIEW

**Comment by pschatzmann** [comment]
I don't quite understand: what is the purpose of this ?

**Comment by degnarraer** [comment]
I would like to drive a GUI to know when the bluetooth source is "searching for devices"

**Comment by pschatzmann** [comment]
Woudn't it be simple just to provie a corresponding get method: the corresponding field already exists...

**Comment by degnarraer** [comment]
I should continuously poll the class to know if it is in discovery mode?
When the class is the one that knows when it changes?

**Comment by pschatzmann** [comment]
Sometimes this would make more sense and would lead to fewer lines of code in your sketch.
If you still think that you need a callback, then I suggest to offer both options...

**Comment by pschatzmann** [comment]
Please note, after regenerarting the documentation, I decided to rename you method from

   set_bt_discovery_mode_callback

to 

   set_discovery_mode_callback

**Comment by degnarraer** [comment]
Sweet

**Comment by degnarraer** [comment]
You added the callback to the common .h file. I am wondering if it should only be added to the bt source h file. I do not think the sink has the discovery mode. It could be confusing to people. Let me know what you think.

**Comment by pschatzmann** [comment]
I don't understand: the methods have been added to BluetoothA2DPSource.h

**Pull request merged**
