### PR TITLE
Active State

### PR DESCRIPTION
**Pull request by podaen**
Active State added

### CODE REVIEW

**Comment by pschatzmann** [comment]
I think this is getting too confusing: I suggest that you use the existing

- get_connection_state () or is_connected()
- get_audio_state ()

depending on what you want to achieve...

**Comment by podaen** [comment]
is need to be sure this is done

> 		a2dp_sink.stop();
> 		a2dp_sink.end();

get_connection_state () and is_connected() is the same I think. 
```
bool IsA2DPActive() {
	if (a2dp_sink.isActive() == true) {
		return true;
	}
	else
	{
		return false;
	}
}
bool IsA2DPConnected() {
	if (a2dp_sink.is_connected() != IntConnected) {
		IntConnected = a2dp_sink.is_connected();
		if (IntConnected == 0) {
			//Serial.println("Not Connected");
		}
		if (IntConnected == 1) {
			Serial.println("Connected");
		}
	}
	return IntConnected;
}
bool IsA2DPPlaying() {
	bool BlnPlaying = false;
	if (a2dp_sink.get_audio_state() != IntStat) {
		IntStat = a2dp_sink.get_audio_state();
		if (IntStat == 0) {
			Serial.println("Stop");
			//Serial.println(IntBufferCounter);
			//for (int i = 0; i < IntBufferCounter;i++) {
			//	if (IntValues[i] != 0) {
			//		Serial.println(IntValues[i]);
			//	}
			//}
			//memset(IntValues, 0, sizeof(IntValues));
			//IntBufferCounter = 0;
		}
		if (IntStat == 2) {
			Serial.println("Play");
			BlnPlaying = true;
		}
	}
	return BlnPlaying;
}
```
I want to close down the esp-a2dp library to start the player from audiotools

**Comment by podaen** [comment]
you mean folowing this example...

[if (a2dp_sink.get_audio_state()==ESP_A2D_AUDIO_STATE_STARTED){](https://github.com/pschatzmann/ESP32-A2DP/blob/main/examples/bt_music_receiver_with_metadata/bt_music_receiver_with_metadata.ino)

I will try it thursday. Please do not close this yet.

**Comment by pschatzmann** [comment]
I am still not sure if I understand the problem correctly: If you want to shut down A2DP, I suggest to just call end() w/o calling stop() first...

**Comment by podaen** [comment]
Maybe I have to add more resistors like I did with an other project with displays before. I nothest that the sd drive doesn't work anymore after reboot with multiple devices on the same spi.

**Comment by podaen** [comment]
Can't resolve the confilicts with the changes on my code lines. I am forced to undo all my changes I have made.

**Pull request closed without merging**
