### PR TITLE
Changes required for dependency update

### PR DESCRIPTION
**Pull request by rbuehlma**
This simplifies the usage of a newer esp-idf version

### CODE REVIEW

**Comment by pschatzmann** [comment]
Just to double check - this is not for the latest ESP32 Arduino support but to be used only in the Expressive IDF
right?

**Comment by rbuehlma** [comment]
Actually I'm quite new to the ESP32 universe and not sure how this all works together.

As far as I understand, the default Expressive IDF which is provided by Arduino contains the API changes which require these changes. Most of these were already in you code but commented out in favor of the old API. I have just added a compile variable which allows to switch between these version without the need to change multiple files.

I would prefer, If there was some automated way to detect the IDF version or at least move the #define to the local project but I did not find a solution for both.

**Comment by pschatzmann** [comment]
Hmm, that's strange. If you check in the Arduino Boards Manager - What version are you using ?
I am on the latest version 1.0.6 and I do not require these changes.

I am still trying to understand the differenence between your way of working and mine...

**Comment by rbuehlma** [comment]
Is it this one?

image

**Comment by rbuehlma** [comment]
Oh, now I understand. This was the wrong board. I'm using a Lolin D32 (ESP32) and have added the espressif for ESP32 manually to Arduino. This is why I'm using a newer version of espressif. I believe Lolin D32 is not supported by the older espressif

**Comment by pschatzmann** [comment]
Just double checked - the Lolin D32 out of the box is compiling.
I am curious - How did you manage to upgrade the espressif release within Arduino ?

**Comment by rbuehlma** [comment]
I have checked out the espressif Repository into this folder:

`~/Arduino/hardware/espressif/esp32/`
This was enough for the Arduino IDE to detect the board

**Pull request merged**
