### PR TITLE
fixed compile error

### PR DESCRIPTION
**Pull request by degnarraer**
Please check my work, but a simple fix allowed it to compile. Not sure what happened.

### CODE REVIEW

**Comment by pschatzmann** [comment]
No, why would you remove the rsp_code from the log and add the rsp_code twice.
What is the error message that you want to address ?

**Comment by pschatzmann** [comment]
I am closing this, since I did not get any answer.

**Comment by degnarraer** [comment]
In file included from C:/GitRepos/ESP32-A2DP/src/BluetoothA2DPCommon.h:68,
                 from C:/GitRepos/ESP32-A2DP/src/BluetoothA2DPSource.h:22,
                 from C:/GitRepos/ESP32-A2DP/src/BluetoothA2DPSource.cpp:16:
C:/GitRepos/ESP32-A2DP/src/BluetoothA2DPSource.cpp: In member function 'virtual void BluetoothA2DPSource::bt_av_hdl_avrc_ct_evt(uint16_t, void*)':
C:/GitRepos/ESP32-A2DP/src/BluetoothA2DPSource.cpp:976:69: error: 'struct esp_avrc_ct_cb_param_t::avrc_ct_psth_rsp_param' has no member named 'rsp_code'; did you mean 'key_code'?
         rc->psth_rsp.key_code, rc->psth_rsp.key_state, rc->psth_rsp.rsp_code);
                                                                     ^~~~~~~~
C:/Users/degna/.platformio/packages/framework-arduinoespressif32@3.20003.220626/cores/esp32/esp32-hal-log.h:127:72: note: in definition of macro 'log_i'
 #define log_i(format, ...) log_printf(ARDUHAL_LOG_FORMAT(I, format), ##__VA_ARGS__)
                                                                        ^~~~~~~~~~~
C:/GitRepos/ESP32-A2DP/src/BluetoothA2DPSource.cpp:973:5: note: in expansion of macro 'ESP_LOGI'
     ESP_LOGI(
     ^~~~~~~~
*** [.pio\build\esp32dev2\libd83\src\BluetoothA2DPSource.cpp.o] Error 1

**Comment by degnarraer** [comment]
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev2]
platform = espressif32@5.0
framework = arduino
board = esp32dev
board_build.partitions = partitions.csv

upload_port = COM4
upload_speed = 500000
monitor_port = COM4
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags = -std=gnu++17
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CORE_DEBUG_LEVEL=3
    -D BUILD_BLUETOOTH
build_unflags = -std=gnu++11

lib_extra_dirs = ../Libraries/CommonClasses

                 ../Libraries
                 ../../../ESP32-A2DP ;Eventually remove this in favor of the lib_dep

lib_deps =
    Arduino_JSON
    GoogleTest
	;https://github.com/degnarraer/ESP32-A2DP.git#main

**Comment by degnarraer** [comment]
I assume the issue is that I am stuck on platform = espressif32@5.0

**Comment by pschatzmann** [comment]
Please try to replace your local copy with an actual lib_deps to confirm that the issue has not been fixed already.
Your correction is still wrong!

**Comment by degnarraer** [comment]
I get the same compile error when I have this platformio:

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev2]
platform = espressif32@5.0
framework = arduino
board = esp32dev
board_build.partitions = partitions.csv

upload_port = COM4
upload_speed = 500000
monitor_port = COM4
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags = -std=gnu++17
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CORE_DEBUG_LEVEL=3
    -D BUILD_BLUETOOTH
build_unflags = -std=gnu++11

lib_extra_dirs = ../Libraries/CommonClasses
                 ../Libraries

lib_deps =
    Arduino_JSON
    GoogleTest
	https://github.com/pschatzmann/ESP32-A2DP.git#main

**Comment by pschatzmann** [comment]
OK, I see, but I don't quite understand why you want to use espressif32@5.0 which was never supported by Arduino ?

- ESP 32 Arduino v2.0.16 was using ESP-IDF v4.4.7
- ESP 32 Arduino v3.0 was using ESP-IDF 5.1
- ESP 32 Arduino v3.0.4 is using ESP-IDF 5.1.4
- ESP 32 Arduino v3.1 will be using ESP-IDF 5.3

If you insist on using this then maybe the correct way to fix this is with a specific 

#if ESP_IDF_VERSION <= ESP_IDF_VERSION_VAL(5, 1, 0)
#else
#endif

**Comment by degnarraer** [comment]
I am generally terrible at this... which is why I do it for a hobby to try to get better at it. Somewhere along the way, they screwed up PSRAM support for the the ESP32 wrover-e. ESP-IDF 5.0 is the latest IDF that also still initializes the sp ram properly. Thank you for assisting me and my journey to get better at this.

**Comment by pschatzmann** [comment]
Never used PSRAM with platformio. Did you add   -DBOARD_HAS_PSRAM ?

**Comment by degnarraer** [comment]
I pushed up the suggested change to the same branch

**Comment by degnarraer** [comment]
Yes, you can see it in the platform IO I am using above. psram on the esp wrover e is a nightmare... and the internet is NO help on it. At some point in time, they just broke it after idf 5.0 and no one noticed. I assume it is the Arduino side of it that is broken but I am not smart enough to figure it out. 

**if I use IDF @5.0:**
[  1241][I][main.cpp:92] OutputSystemStatus(): [SystemStatus] Xtal Clock Frequency: 40 MHz
[  1249][I][main.cpp:93] OutputSystemStatus(): [SystemStatus] CPU Clock Frequency: 240 MHz
[  1257][I][main.cpp:94] OutputSystemStatus(): [SystemStatus] Apb Clock Frequency: 80000000 Hz
[  1265][I][main.cpp:95] OutputSystemStatus(): [SystemStatus] Total heap: 251968
[  1273][I][main.cpp:96] OutputSystemStatus(): [SystemStatus] Free heap: 112972
[  1280][I][main.cpp:97] OutputSystemStatus(): [SystemStatus] **Total PSRAM: 4192067**
[  1287][I][main.cpp:98] OutputSystemStatus(): [SystemStatus] **Free PSRAM: 4172915**

**if I use latest IDF**
[   458][I][main.cpp:92] OutputSystemStatus(): [SystemStatus] Xtal Clock Frequency: 40 MHz
[   466][I][main.cpp:93] OutputSystemStatus(): [SystemStatus] CPU Clock Frequency: 240 MHz
[   474][I][main.cpp:94] OutputSystemStatus(): [SystemStatus] Apb Clock Frequency: 80000000 Hz
[   482][I][main.cpp:95] OutputSystemStatus(): [SystemStatus] Total heap: 240952
[   490][I][main.cpp:96] OutputSystemStatus(): [SystemStatus] Free heap: 82460
[   497][I][main.cpp:97] OutputSystemStatus(): [SystemStatus] **Total PSRAM: 0**
[   504][I][main.cpp:98] OutputSystemStatus(): [SystemStatus] **Free PSRAM: 0**

**Comment by pschatzmann** [comment]
Not sure if this is your issue: but your syntax is wrong: there should not be any space after -D

**Comment by degnarraer** [comment]
I have tried 50000 things over the last few years... that change made no difference. :-) Appreciate working with you!

**Pull request closed without merging**
