### PR TITLE
Remove warnings, fix failing examples, Github Action to auto compile examples as CI

### PR DESCRIPTION
**Pull request by designer2k2**
Hello,

this PR makes 3 things:
- removes all warnings
- fixes failing examples
- provides a Github Action that compiles every example on every future pull/push, making a minimalistic CI/CD.

### Warnings

as mentioned here https://github.com/pschatzmann/ESP32-A2DP/issues/355 it fails to compile due to warnings.  (when show warnings is active)

This is solved by adding [[maybe_unused]] in the src/BluetoothA2DPSource.cpp.  And by adding missing initializers with their default values into src/BluetoothA2DPSink.cpp

### Failing examples

the first failing is just a file rename, it did not match the folder it was in: examples/bt_music_receiver_disconnect-reconnect/bt_music_receiver_disconnect-reconnect.ino

The second im not shure about the fix: examples/bt_music_receiver_minram/bt_music_receiver_minram.ino  i renamed `BluetoothA2DPSinkMinRAM`  as it does not exist.

### Github Action to compile all examples

This can help to find future issues faster, the Github Action runs automatically on every push or pull request. It uses the latest arduino-esp32 to compile all examples.  

The last run on my fork shows how this works: https://github.com/designer2k2/ESP32-A2DP/actions/runs/4017288190/jobs/6901442821#step:3:49

### CODE REVIEW

**Comment by pschatzmann** [comment]
Cool, I just have one concearn: are you sure that your changes compile with older ESP versions. Can you do a quick test with 1.0.6 ?

**Comment by designer2k2** [comment]
miniram is removed.

But it fails for 1.0.6, see here: https://github.com/designer2k2/ESP32-A2DP/actions/runs/4018906129/jobs/6905094143#step:3:101

` /home/runner/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:43:30: error: 'I2S_MCLK_MULTIPLE_DEFAULT' was not declared in this scope`

The defaults i used do not exist in this old version.

Is support for 1.0.6 needed?  If so then i will see how to handle both, the latest and the 1.0.6. (no idea right now how, but google will tell me :-) )

I would then also extend the CI to run for both versions automatically.

**Comment by pschatzmann** [comment]
CI on the most recent version is ok.
I suggest that you just wrap the offending lines in 
#ifdef ESP_IDF_4
#endif

**Comment by designer2k2** [comment]
yes that works!
It compiles for 1.0.6: https://github.com/designer2k2/ESP32-A2DP/actions/runs/4019021493/jobs/6905350408#step:3:135
(with some other warnings, but they are not treated as error, so i would leave them as they only show on 1.0.6)

and this is the run with this changes and 2.0.6: https://github.com/designer2k2/ESP32-A2DP/actions/runs/4019063559/jobs/6905445580#step:3:49
(no warnings)

**Pull request merged**
