### PR TITLE
Adding option to specify device name

### PR DESCRIPTION
**Pull request by jmsunseri**
addresses issue #456

### CODE REVIEW

**Comment by pschatzmann** [comment]
I rather think that the existing set_local_name() method is wrong.
What exactly is your method doing ?

**Comment by jmsunseri** [comment]
I'm just setting the dev_name variable so that later on 

```
case BT_APP_EVT_STACK_UP: {
            // set up device name 
            esp_bt_dev_set_device_name(dev_name);
```

it will get picked up.  

the existing set_local_name method seems to do something else doesn't it?

**Comment by pschatzmann** [comment]
I think It is supposed to do exactly that: To provide the local name

**Comment by jmsunseri** [comment]
I don't mind that at all.

**Comment by jmsunseri** [comment]
That is the fastest github MR i have ever seen!  Thank you!

**Pull request merged**
